### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by maojinyang** [FreddeFrallan/Non-Residual-Prompting#1]
Thank you for your excellent work! Do you have a plan to release training code？

**Comment by FreddeFrallan** [comment]
Thank you.
I could probably get around to uploading the training code up this weekend if there's interest 

However, we're currently working on follow-up work for this, where we have transferred the code base into PyTorch. Not sure I have time to clean up both the TF and PT version. Which one would you prefer?

**Comment by maojinyang** [comment]
PT version, thank you so much!

**Comment by FreddeFrallan** [comment]
Ok, sorry about the delay.

I have now uploaded a very simplistic implementation and training loop in PyTorch.
You'll have to modify the training scripts if you want them to do anything useful. But hopefully, this should serve as a good starting point.

**Comment by maojinyang** [comment]
Thank you very much！
